// <auto-generated />
using System;
using Digit.DeviceSynchronization.Impl;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DigitService.Migrations.DeviceSynchronization
{
    [DbContext(typeof(DeviceSynchronizationContext))]
    [Migration("20190327152138_DeviceSync")]
    partial class DeviceSync
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("Digit.DeviceSynchronization.Impl.StoredDevice", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OwnerId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Sync_Devices");
                });

            modelBuilder.Entity("Digit.DeviceSynchronization.Impl.StoredSyncAction", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActionId")
                        .IsRequired();

                    b.Property<bool>("Done");

                    b.Property<DateTime>("RequestedFor");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Sync_SyncActions");
                });
#pragma warning restore 612, 618
        }
    }
}
