// <auto-generated />
using DigitService.Impl.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DigitService.Migrations
{
    [DbContext(typeof(DigitServiceContext))]
    [Migration("20180416111836_Devices")]
    partial class Devices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("DigitService.Impl.EF.StoredBatteryMeasurement", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeviceId");

                    b.Property<DateTime>("MeasurementTime");

                    b.Property<uint>("RawValue");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("BatteryMeasurements");
                });

            modelBuilder.Entity("DigitService.Impl.EF.StoredDevice", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("BatteryCutOffVoltage");

                    b.Property<double>("BatteryMaxVoltage");

                    b.Property<double>("BatteryMeasurmentRange");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DigitService.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PushChannel");

                    b.Property<string>("ReminderId");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DigitService.Impl.EF.StoredBatteryMeasurement", b =>
                {
                    b.HasOne("DigitService.Impl.EF.StoredDevice", "Device")
                        .WithMany("BatteryMeasurements")
                        .HasForeignKey("DeviceId");
                });

            modelBuilder.Entity("DigitService.Impl.EF.StoredDevice", b =>
                {
                    b.HasOne("DigitService.Models.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
